name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        MIX_ENV=test mix deps.compile
    - name: Tests
      run: mix test --cover
    - name: Format
      run: mix format --check-formatted --check-equivalent
    - name: Lint
      run: mix credo
